### ISSUE TITLE
Question: Placement of Series Id

### ISSUE THREAD

**Issue by Buried-In-Code** [Metron-Project/metroninfo#17]
Any reason the Series Id is attached to the Series name and not the Series object itself?
https://github.com/Metron-Project/metroninfo/blob/cff0f08c0703af0bb12e90d33f2b0d3598483540/drafts/v1.0/Sample.xml#L5-L10

**Comment by bpepple** [comment]
No specific reason and it does make sense to move the ID to the parent element. Also, most likely I'll need to look at the other resources (arcs, characters, etc) to make sure they follow suit.
