### ISSUE TITLE
Add Marvel as Information Source

### ISSUE THREAD

**Issue by Buried-In-Code** [Metron-Project/metroninfo#20]
To support use of [esak](https://github.com/Metron-Project/esak) with MetronInfo it would be nice to have "Marvel" in the enum list

https://github.com/Metron-Project/metroninfo/blob/67120632ff865f85c2b39a2e871e7cb61e7a8d52/drafts/v1.0/MetronInfo.xsd#L205-L212

**Comment by bpepple** [comment]
Sounds list a good idea. I've got a funeral to go to today, but I'll add it later this week.
