### ISSUE TITLE
Update Format Enum

### ISSUE THREAD

**Issue by Buried-In-Code** [Metron-Project/metroninfo#22]
The list of Formats that Metron supports doesn't match the list that this schema has:

- [ ] Canceled Series
- [x] Hard Cover

It'd also be good if the 2 had matching values to easily handle converting Metron to schema such as:
- [x] `Limited` (Schema) - `Limited Series` (Metron)

**Comment by bpepple** [comment]
> The list of Formats that Metron supports doesn't match the list that this schema has:
> 
>     * [ ]  Canceled Series
> 
I didn't include this, since my thinking is the **Series** type would be used for ___Ongoing___ and ___Cancelled___ series. I've thought about making this change on Metron also but wanted to give it more thought before implementing the change.

**Comment by bpepple** [comment]
> It'd also be good if the 2 had matching values to easily handle converting Metron to schema such as:
> 
>     * [ ]  `Limited` (Schema) - `Limited Series` (Metron)

I think it makes more sense to change this at _Metron_ to `Limited`, since the ___Series___ is a bit redundant.
