### ISSUE TITLE
Add `lastUpdated`

### ISSUE THREAD

**Issue by Buried-In-Code** [Metron-Project/metroninfo#34]
Having some kind of date or timestamp element/attribute to know how up to date the information is.
It'd be useful when using different tagging tools so as they know wether or not to refresh the information.

**Comment by bpepple** [comment]
Good catch! So, this should most likely be a top-level element but I'm not sure what the element name should be **LastUpdated** or **LastModified**. I'm leaning towards **LastModified**, but what are your thoughts?

**Comment by Buried-In-Code** [comment]
To me they're all interchangeable so they'd all work, but you're right `lastModified` seems a better fit than lastUpdated
